### ISSUE TITLE
edgedb:nightly raises RuntimeError: not connected 

### ISSUE THREAD

**Issue by isidentical** [edgedb/edgedb-docker#7]
```
 $ docker run -it edgedb/edgedb:nightly
Unable to find image 'edgedb/edgedb:nightly' locally
nightly: Pulling from edgedb/edgedb
6ec7b7d162b2: Pull complete 
97120319636a: Pull complete 
1ba1d0ed5747: Pull complete 
Digest: sha256:cfbd9c29acc9cf998d0daeb76356e3d05ccd51dbad05b333ecdc66153b6ca096
Status: Downloaded newer image for edgedb/edgedb:nightly
Bootstrapping EdgeDB instance...
WARNING: unsolicited message LogMessage(LogMessage { severity: Debug, code: 4026531840, text: "received configuration reload request", attributes: {} })
OK: CONFIGURE SYSTEM
edgedb error: ERROR: InternalServerError: not connected
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/mng_port/edgecon.pyx", line 1625, in edb.server.mng_port.edgecon.EdgeConnection.main
        File "edb/server/mng_port/edgecon.pyx", line 893, in simple_query
        File "edb/server/mng_port/edgecon.pyx", line 953, in _simple_query
        File "edb/server/pgcon/pgcon.pyx", line 235, in signal_sysevent
        File "edb/server/pgcon/pgcon.pyx", line 773, in simple_query
        File "edb/server/pgcon/pgcon.pyx", line 1139, in edb.server.pgcon.pgcon.PGProto.before_command
      RuntimeError: not connected
```
```
 $ docker run edgedb/edgedb:nightly  
Bootstrapping EdgeDB instance...
WARNING: unsolicited message LogMessage(LogMessage { severity: Debug, code: 4026531840, text: "received configuration reload request", attributes: {} })
OK: CONFIGURE SYSTEM
edgedb error: ERROR: InternalServerError: not connected
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/mng_port/edgecon.pyx", line 1625, in edb.server.mng_port.edgecon.EdgeConnection.main
        File "edb/server/mng_port/edgecon.pyx", line 893, in simple_query
        File "edb/server/mng_port/edgecon.pyx", line 953, in _simple_query
        File "edb/server/pgcon/pgcon.pyx", line 235, in signal_sysevent
        File "edb/server/pgcon/pgcon.pyx", line 773, in simple_query
        File "edb/server/pgcon/pgcon.pyx", line 1139, in edb.server.pgcon.pgcon.PGProto.before_command
      RuntimeError: not connected
```

However, if I try to use `latest` tag, it works;
```
Bootstrapping EdgeDB instance...
OK: CONFIGURE SYSTEM
OK: CONFIGURE SYSTEM
INFO 1 2020-12-20 10:51:38,473 edb.server: EdgeDB server (1.0-alpha.5+g83a2a4fac.d20200826) starting.
INFO 1 2020-12-20 10:51:41,381 edb.server: Serving on 0.0.0.0:5656
INFO 1 2020-12-20 10:51:41,381 edb.server: Serving on /run/edgedb/.s.EDGEDB.5656
INFO 1 2020-12-20 10:51:41,381 edb.server: Serving admin on /run/edgedb/.s.EDGEDB.admin.5656
```

**Comment by adriangb** [comment]
It looks like this was resolved. I was seeing this on alpha7, but on `1.0-alpha.8+dev.5304.g8b9d2f39)` at least this doesn't seem to happen.

**Comment by isidentical** [comment]
I can verify it works now! Don't know what changed between releases, but the issue for nightly looks resolved. Thanks for letting me know.
