### ISSUE TITLE
1-alpha7 Docker image crashes

### ISSUE THREAD

**Issue by clmno** [edgedb/edgedb-docker#9]
- EdgeDB Version: 1.0 Alpha 7
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Run the latest docker container
```sh
docker run -it --rm -p 5656:5656 edgedb/edgedb:1-alpha7
```
2. Get a `runtime` error
> edgedb error: ERROR: InternalServerError: not connected
```sh
Bootstrapping EdgeDB instance...
WARNING: unsolicited message LogMessage(LogMessage { severity: Debug, code: 4026531840, text: "received configuration reload request", attributes: {} })
OK: CONFIGURE SYSTEM
edgedb error: ERROR: InternalServerError: not connected
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/mng_port/edgecon.pyx", line 1625, in edb.server.mng_port.edgecon.EdgeConnection.main
        File "edb/server/mng_port/edgecon.pyx", line 893, in simple_query
        File "edb/server/mng_port/edgecon.pyx", line 953, in _simple_query
        File "edb/server/pgcon/pgcon.pyx", line 231, in signal_sysevent
        File "edb/server/pgcon/pgcon.pyx", line 769, in simple_query
        File "edb/server/pgcon/pgcon.pyx", line 1050, in edb.server.pgcon.pgcon.PGProto.before_command
      RuntimeError: not connected
```

**Comment by tailhook** [comment]
This looks like have been fixed with backend connection pool implementation, so works on nightly. Original error look like a crash because connection to postgres was interrupted. At least running the following works fine:
```
docker run -it --rm -p 5656:5656 edgedb/edgedb:20210128023945dde634
```

 @elprans, you probably understand older the underlying issue better, so please comment or close the issue.

**Comment by elprans** [comment]
Yes, @1st1 fixed this with connection pool rework.  The original crash was in the internal event sending code.
